apiVersion: apps/v1
kind: Deployment
metadata:
  name: bored-agent
  labels:
    app: bored-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bored-agent
  template:
    metadata:
      labels:
        app: bored-agent
    spec:
      serviceAccountName: bored-agent
      containers:
      - name: agent
        image: bored-agent:latest
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: bored-agent-cert
  labels:
    app: bored-agent
